version: '3.8'
services:
  
  zabbix-build-base:
    build:
    context: ./Dockerfiles/build-base/${UBUNTU_OS_TAG_SHORT}
    cache_from:
      - "${UBUNTU_CACHE_FROM}"
    image: ${BUILD_BASE_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_LOCAL_IMAGE_TAG_POSTFIX}

  zabbix-build-mysql:
    build:
    context: ./Dockerfiles/build-mysql/${UBUNTU_OS_TAG_SHORT}
    cache_from:
      - "${UBUNTU_CACHE_FROM}"
    args:
      BUILD_BASE_IMAGE: ${BUILD_BASE_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_LOCAL_IMAGE_TAG_POSTFIX}
    image: ${BUILD_BASE_MYSQL_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_LOCAL_IMAGE_TAG_POSTFIX}
    depends_on:
      - zabbix-build-base

  zabbix-server:
    build:
      context: ./Dockerfiles/build-base/${UBUNTU_OS_TAG_SHORT}
    cache_from:
      - "${UBUNTU_CACHE_FROM}"
    image: zabbix-server-mysql:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_LOCAL_IMAGE_TAG_POSTFIX}
    depends_on:
    ports:
      - "${ZABBIX_SERVER_PORT}:10051"
    restart: "${RESTART_POLICY}"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${DATA_DIRECTORY}/usr/lib/zabbix:ro   
    tmpfs: /tmp
    ulimits:
       nproc: 65535
       nofile:
       soft: 20000
       hard: 40000
    deploy:
    resources:
      limits:
        cpus: '0.70'
        memory: 1G
    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_srv
    networks:
      zbx_net_database:
        aliases:
          - zabbix-server
      zbx_net_backend:
        aliases:
          - zabbix-server
      zbx_net_frontend:
    stop_grace_period: 30s
    sysctls:
      - net.ipv4.ip_local_port_range=1024 64999
      - net.ipv4.conf.all.accept_redirects=0
      - net.ipv4.conf.all.secure_redirects=0
      - net.ipv4.conf.all.send_redirects=0
    labels:
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-server"


  mysql-server:
    #extends:
      #service: server
    build:
      context: ./Dockerfiles/build-mysql/${UBUNTU_OS_TAG_SHORT}
    cache_from:
      - "${UBUNTU_CACHE_FROM}" 
    args:
      BUILD_BASE_IMAGE: ${BUILD_BASE_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_LOCAL_IMAGE_TAG_POSTFIX}
    image: ${BUILD_BASE_MYSQL_IMAGE}:${ZABBIX_UBUNTU_IMAGE_TAG}${ZABBIX_LOCAL_IMAGE_TAG_POSTFIX}
    depends_on:
      - zabbix-server
#   - dbsocket:/var/run/mysqld/
    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_db_mysql
    secrets:
      - MYSQL_USER
      - MYSQL_PASSWORD
#   - client-key.pem
#   - client-cert.pem
#   - root-ca.pem
    networks:
    zbx_net_backend:
      aliases:
        - zabbix-server-mysql
    labels:
      com.zabbix.description: "Zabbix server with MySQL database support"
      com.zabbix.dbtype: "mysql"

 
  networks:
   zbx_net_database:
     aliases:
      - zabbix-proxy-mysql
   zbx_net_backend:
    aliases:
     - zabbix-proxy-mysql
  labels:
   com.zabbix.description: "Zabbix proxy with MySQL database support"
   com.zabbix.dbtype: "mysql"

web:
  ports:
    - "${ZABBIX_WEB_NGINX_HTTP_PORT}:8080"
    - "${ZABBIX_WEB_NGINX_HTTPS_PORT}:8443"
  restart: "${RESTART_POLICY}"
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - ${DATA_DIRECTORY}/etc/ssl/nginx:/etc/ssl/nginx:ro
    - ${DATA_DIRECTORY}/usr/share/zabbix/modules/:/usr/share/zabbix/modules/:ro
  tmpfs: /tmp
  deploy:
    resources:
      limits:
      cpus: '0.70'
      memory: 512M

    env_file:
      - ${ENV_VARS_DIRECTORY}/.env_web
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    start_period: 30s
    networks:
      zbx_net_database:
      zbx_net_backend:
      zbx_net_frontend:
    stop_grace_period: 10s
    sysctls:
      - net.core.somaxconn=65535
    labels:
      com.zabbix.company: "Zabbix LLC"
      com.zabbix.component: "zabbix-frontend"
      com.zabbix.webserver: "nginx"

 web-nginx-mysql:
  extends:
   service: web-nginx
#  volumes:
#   - dbsocket:/var/run/mysqld/
  env_file:
   - ${ENV_VARS_DIRECTORY}/.env_db_mysql
  secrets:
   - MYSQL_USER
   - MYSQL_PASSWORD
#   - client-key.pem
#   - client-cert.pem
#   - root-ca.pem
  networks:
   zbx_net_backend:
    aliases:
     - zabbix-web-nginx-mysql
  labels:
   com.zabbix.description: "Zabbix frontend on Nginx web-server with MySQL database support"
   com.zabbix.dbtype: "mysql"

 